### ISSUE TITLE
Typo - Section 1.5

### ISSUE THREAD

**Issue by chorgan182** [b-rodrigues/rap4all#22]
https://github.com/b-rodrigues/rap4all/blob/4a4f7cdf2af627a70933e7d166fdefe1e450bbaa/intro.qmd#L353

Thank you for the book! I'm loving the message so far. I'm always trying to explain this concept to newer R-programmers reluctant to learn git or document code, and now I have a much better resource :)

I know you are still working on it, but I figured I'd point out anything I see to save you some time. I don't mean to nitpick, just trying to help.

Anyway, the line above is missing a "be".

> So what does this all mean? This means that reproducibility is on a continuum,
> and depending on the constraints you face your project can _**be**_ not very reproducible
> to totally reproducible.

**Comment by b-rodrigues** [comment]
Hi, many thanks! I’ve fixed it, it’ll be online with the next push :)
If you’re familiar with Git, you can also clone the repo and submit PRs for fixes directly (if you prefer), or you can use issues as well, whatever works for you!
