### ISSUE TITLE
Consider adding Github links in book

### ISSUE THREAD

**Issue by parmsam** [b-rodrigues/rap4all#23]
Similar to [R4DS 2e](https://r4ds.hadley.nz/).

Reference links:
* https://quarto.org/docs/books/book-output.html#sidebar-tools
* https://github.com/hadley/r4ds/blob/43d80e79b0c062a5d4b94b9188cef70e30bcba7a/_quarto.yml#L18-L20

**Comment by b-rodrigues** [comment]
Hi Sam

thanks  for the suggestion, that was indeed needed! It has been fixed with 4535aa33eab6db83028348d950590dcf16303a0e

Cheers!
