### ISSUE TITLE
Thousands marker

### ISSUE THREAD

**Issue by jonathandmoore** [b-rodrigues/rap4all#24]
Hello Bruno, I took up your challenge from Mastodon to read a bit of your draft.  One thing that stands out is how you use the . separator rather than , separator for 000s.  e.g. 400.000 rather than 400,000.  As a native English reader, I usually expect to see the , and the . is used as a decimal point.  If I do a PR with typos, do you want me to mark these for change also?

**Comment by b-rodrigues** [comment]
Hello Jonathan

that is a very good point! I would be very grateful if you could do a PR fixing this ! Many thanks

**Comment by jonathandmoore** [comment]
https://github.com/b-rodrigues/rap4all/pull/25

**Comment by jonathandmoore** [comment]
I left the issue open in case it's in any other modules
