### ISSUE TITLE
Associate Acronyms with their definition

### ISSUE THREAD

**Issue by AlainVagner** [b-rodrigues/rap4all#31]
In the preface, you use some acronyms like ONS, RAP, PI, etc. The text could be easier to read if they would be associated with their definition, at least for their first appearance, ex: Office for National Statistics (ONS).
Some of them are not defined, ex: Principal Investigator (PI). I don't know if this is so well known outside of R&D circles.

**Comment by b-rodrigues** [comment]
That is a very good point, I will go through them all!
