### ISSUE TITLE
Why do we need to use an anonymous function?

### ISSUE THREAD

**Issue by JT-39** [b-rodrigues/rap4all#42]
Hi Bruno, 

In 6.3.4 Data frames, the code:

`nested_unemp %>%
  mutate(nrows = map(data, \(x)filter(x, year == 2015)))`

Why do we need to use an anonymous function? Would it not work fine as:

`nested_unemp %>%
  mutate(nrows = map(data, function(x){filter(x, year == 2015)}))`

**Comment by b-rodrigues** [comment]
What you suggest is also an anonymous function, \(x) is a shorthand for function(x)

**Comment by JT-39** [comment]
Ahh I see, my mistake! I thought an anonymous function was using the notation \(x) only. But now I understand it is a function that is not assigned to a variable. Thanks :)

**Comment by JT-39** [comment]
Ahh I see, my mistake! I thought an anonymous function was using the notation \(x) only. But now I understand it is a function that is not assigned to a variable. Thanks :)
