### ISSUE TITLE
Renv not working in targets-minimal repo

### ISSUE THREAD

**Issue by JT-39** [b-rodrigues/rap4all#44]
Hi Bruno, 

I have cloned your repo - targets-minimal, activated renv using `renv::activate()` and then ran `renv::restore()`. The packages download but do not install. I get the following error message from trying to install the `MASS` package:

```
Installing MASS ...                           FAILED
Error: Error installing package 'MASS':
================================

* installing *source* package ‘MASS’ ...
** package ‘MASS’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C compiler: ‘Apple clang version 14.0.0 (clang-1400.0.29.202)’
using SDK: ‘MacOSX13.1.sdk’
clang -arch x86_64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c MASS.c -o MASS.o
MASS.c:37:23: error: unknown type name 'Sint'; did you mean 'int'?
```

With a load more error output. I am wondering wether this is because I am using a newer version of R (R 4.3.1) and renv (renv 1.0.2). Or should this still work?

Thanks
Jake

**Comment by b-rodrigues** [comment]
yes restoring may fail as explained just below

Sent from ProtonMail mobile

-------- Original Message --------
