### ISSUE TITLE
Data as plural rather than singular

### ISSUE THREAD

**Issue by matanhakim** [b-rodrigues/rap4all#7]
Formally, "data" is considered a plural noun.
For example, see here: https://www.britannica.com/dictionary/eb/qa/Is-Data-Singular-or-Plural-

Nevertheless, it is common for people to use it as a singular noun. I think this is a decision that needs to be taken by you, and to be implemented consistently throughout the book, so I won't open PRs on this manner.

**Comment by b-rodrigues** [comment]
Hi, thanks for pointing this out! I will indeed need to harmonize this.
